version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.5.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "O2QohMP08ACQo-QZv3ExCRw23DmBuLBcyc5M14QfVaI="
    depends_on:
      - postgres
    command: ["airflow", "db", "init"]

  webserver:
    image: apache/airflow:2.5.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "O2QohMP08ACQo-QZv3ExCRw23DmBuLBcyc5M14QfVaI="
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    command: ["bash", "-c", "sleep 10 && airflow webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts  # Mapeando a pasta de scripts

  scheduler:
    image: apache/airflow:2.5.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "O2QohMP08ACQo-QZv3ExCRw23DmBuLBcyc5M14QfVaI="
    depends_on:
      - postgres
      - airflow-init
    command: ["bash", "-c", "sleep 10 && airflow scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts  # Mapeando a pasta de scripts

volumes:
  postgres_data:
